# Generated by Django 4.1.6 on 2023-03-04 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=50)),
                ('scientific_name', models.CharField(max_length=100)),
                ('in_extinction', models.BooleanField(default=False)),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.family')),
                ('zoo_id', models.ManyToManyField(to='zoo.zoo')),
            ],
        ),
    ]
