# Generated by Django 4.1.6 on 2023-03-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='zoo_id',
        ),
    ]
