# Generated by Django 4.1.6 on 2023-03-05 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_animalregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalregistration',
            name='zoo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zoo', to='zoo.zoo'),
        ),
    ]
