# Generated by Django 4.1.6 on 2023-03-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_alter_animalregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalregistration',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
    ]
