# Generated by Django 4.1.6 on 2023-03-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_remove_animal_zoo_id'),
        ('zoo', '0005_animalregistration_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='animlal',
            field=models.ManyToManyField(to='animal.animal'),
        ),
        migrations.DeleteModel(
            name='AnimalRegistration',
        ),
    ]
