# Generated by Django 4.1.6 on 2023-03-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0006_zoo_animlal_delete_animalregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoo',
            old_name='animlal',
            new_name='animal',
        ),
    ]
