# Generated by Django 4.1.6 on 2023-03-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0007_rename_animlal_zoo_animal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoo',
            old_name='animal',
            new_name='animals',
        ),
    ]
