# Generated by Django 4.1.6 on 2023-03-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0008_rename_animal_zoo_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoo',
            name='surface',
            field=models.DecimalField(decimal_places=2, help_text='m2', max_digits=10),
        ),
    ]
