# Generated by Django 4.1.6 on 2023-03-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0009_alter_zoo_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoo',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='Anual', max_digits=20),
        ),
    ]
