# Generated by Django 4.1.6 on 2023-03-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0010_alter_zoo_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zoo',
            name='animals',
        ),
    ]
