# Generated by Django 4.1.6 on 2023-03-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0011_alter_zoo_options_zooanimal_alter_zoo_animals'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zooanimal',
            table=None,
        ),
    ]
