# Generated by Django 4.1.6 on 2023-03-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0012_alter_zooanimal_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zooanimal',
            old_name='animal_id',
            new_name='animal',
        ),
        migrations.RenameField(
            model_name='zooanimal',
            old_name='zoo_id',
            new_name='zoo',
        ),
    ]
