# Generated by Django 4.1.6 on 2023-03-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_remove_animal_zoo_id'),
        ('zoo', '0013_rename_animal_id_zooanimal_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoo',
            name='animals',
            field=models.ManyToManyField(to='animal.animal'),
        ),
        migrations.DeleteModel(
            name='ZooAnimal',
        ),
    ]
