# Generated by Django 4.1.6 on 2023-03-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0014_alter_zoo_animals_delete_zooanimal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoo',
            options={},
        ),
    ]
