# Generated by Django 4.1.6 on 2023-03-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_remove_animal_zoo_id'),
        ('zoo', '0015_alter_zoo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZooAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animal.animal')),
                ('zoo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoo.zoo')),
            ],
            options={
                'verbose_name': 'animal Zoo',
                'verbose_name_plural': 'animales Zoos',
            },
        ),
    ]
