# Generated by Django 4.1.6 on 2023-03-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_remove_animal_zoo_id'),
        ('zoo', '0016_zooanimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoo',
            name='animals',
            field=models.ManyToManyField(blank=True, through='zoo.ZooAnimal', to='animal.animal'),
        ),
    ]
