# Generated by Django 4.1.6 on 2023-03-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_remove_animal_zoo_id'),
        ('zoo', '0018_alter_zooanimal_animal_alter_zooanimal_zoo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zooanimal',
            options={},
        ),
        migrations.AlterField(
            model_name='zooanimal',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animal.animal'),
        ),
        migrations.AlterField(
            model_name='zooanimal',
            name='zoo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoo.zoo'),
        ),
    ]
