# Generated by Django 4.1.6 on 2023-03-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0019_alter_zooanimal_options_alter_zooanimal_animal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zooanimal',
            options={'verbose_name': 'animal Zoo', 'verbose_name_plural': 'animales Zoos'},
        ),
        migrations.RemoveField(
            model_name='zoo',
            name='animals',
        ),
    ]
