# Generated by Django 4.1.6 on 2023-03-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_remove_animal_zoo_id'),
        ('zoo', '0020_alter_zooanimal_options_remove_zoo_animals'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='animals',
            field=models.ManyToManyField(to='animal.animal'),
        ),
        migrations.DeleteModel(
            name='ZooAnimal',
        ),
    ]
